apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: kubernetes-mba-se
spec:
  containers:
  - name: nginx
    image: nginx    
    ports:
      - containerPort: 80
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"